<a href="https://colab.research.google.com/github/XuningZhuang/MSSP6070/blob/main/WeeklyModules/Week04/Week_4_Exercise_Xuning_Zhuang_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving parsed.csv to parsed (1).csv

In [ ]:
import pandas as pd
df = pd.read_csv('parsed.csv')
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [ ]:
# 2a.
df['parsed_place'] == 'Japan'

0       False
1       False
2       False
3       False
4       False
        ...
9327    False
9328    False
9329    False
9330    False
9331    False
Name: parsed_place, Length: 9332, dtype: bool

In [ ]:
df[df['parsed_place'] == 'Japan']

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
67,NaN,NaN,1000hbqa,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.415,NaN,72.0,",us1000hbqa,",4.6,mb,...,reviewed,1539448501800,"M 4.6 - 160km NNW of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",480.0,1539449501040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
476,NaN,4.1,1000haxq,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.168,59.0,97.0,",us1000haxq,",5.2,mww,...,reviewed,1539317747370,"M 5.2 - 7km ESE of Asahi, Japan",0,earthquake,",dyfi,geoserve,moment-tensor,origin,phase-data,",540.0,1539428158785,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
536,NaN,2.7,1000haw5,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.186,2.0,64.0,",us1000haw5,",4.5,mwr,...,reviewed,1539303265990,"M 4.5 - 14km E of Tomakomai, Japan",0,earthquake,",dyfi,geoserve,moment-tensor,origin,phase-data,",540.0,1539311606738,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
713,NaN,NaN,1000hah8,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.141,NaN,82.0,",us1000hah8,",4.7,mb,...,reviewed,1539238726290,"M 4.7 - 139km WSW of Naze, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539240344040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1124,NaN,NaN,1000h9la,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.737,NaN,135.0,",us1000h9la,",4.6,mb,...,reviewed,1539115120470,"M 4.6 - 53km ESE of Kamaishi, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539119067040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1309,NaN,NaN,1000h952,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.897,NaN,136.0,",us1000h952,",4.5,mb,...,reviewed,1539058606580,"M 4.5 - 80km ENE of Misawa, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539060436040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1398,NaN,NaN,1000h8zx,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.555,NaN,124.0,",us1000h8zx,",4.4,mb,...,reviewed,1539034912990,"M 4.4 - 65km NNE of Hachijo-jima, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539062940040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1422,NaN,1.0,1000h8xg,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.686,1.0,129.0,",us1000h8xg,",4.7,mb,...,reviewed,1539028322670,"M 4.7 - 41km E of Namie, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1539061047807,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1435,NaN,NaN,1000h8vs,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.152,NaN,72.0,",us1000h8vs,",4.4,mb,...,reviewed,1539020712670,"M 4.4 - 21km E of Tomakomai, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539034924040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1492,NaN,3.4,1000h8q7,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.059,4.0,74.0,",us1000h8q7,",4.6,mb,...,reviewed,1539003238480,"M 4.6 - 29km E of Tomakomai, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1539012243124,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1563,NaN,NaN,1000h8mj,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.773,NaN,101.0,",us1000h8mj,",4.9,mb,...,reviewed,1538977532250,"M 4.9 - 293km ESE of Iwo Jima, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1538978864040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1732,NaN,NaN,1000hb41,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.308,NaN,154.0,",us1000hb41,",4.1,mb,...,reviewed,1538923896600,"M 4.1 - 89km NE of Miyako, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1539532511040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1875,NaN,NaN,1000h8c2,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.570,NaN,82.0,",us1000h8c2,",4.7,mb,...,reviewed,1538881270700,"M 4.7 - 177km WSW of Chichi-shima, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538882370040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
1898,NaN,3.8,1000h8b9,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.516,19.0,66.0,",us1000h8b9,",4.8,mb,...,reviewed,1538874859870,"M 4.8 - 12km N of Shinshiro, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1539319234277,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2053,NaN,NaN,1000h84n,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.108,NaN,85.0,",us1000h84n,",4.8,mb,...,reviewed,1538839123780,"M 4.8 - 147km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538840634040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2191,NaN,2.7,1000h800,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.134,1.0,75.0,",us1000h800,",4.6,mb,...,reviewed,1538799265130,"M 4.6 - 27km ESE of Chitose, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538811844812,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2564,NaN,NaN,1000hams,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.187,NaN,118.0,",us1000hams,",4.6,mb,...,reviewed,1538701532340,"M 4.6 - 162km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539306889040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2576,NaN,3.1,1000h7cn,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.015,7.0,33.0,",us1000h7cn,",5.4,mb,...,reviewed,1538697528010,"M 5.4 - 37km E of Tomakomai, Japan",0,earthquake,",dyfi,geoserve,moment-tensor,origin,phase-data,",540.0,1538757701040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2591,NaN,NaN,1000h7bt,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.068,NaN,68.0,",us1000h7bt,",5.0,mww,...,reviewed,1538693073410,"M 5.0 - 144km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538694501040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2688,NaN,NaN,1000hajw,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.539,NaN,41.0,",us1000hajw,",4.0,mb,...,reviewed,1538673414250,"M 4.0 - 51km WNW of Mikuni, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539363073040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
2824,NaN,NaN,1000h6vj,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.125,NaN,131.0,",us1000h6vj,",4.4,mb,...,reviewed,1538641253520,"M 4.4 - 51km SSE of Kushima, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538642265040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
3072,NaN,3.1,1000h6ac,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.082,15.0,118.0,",us1000h6ac,",4.9,mb,...,reviewed,1538579732490,"M 4.9 - 15km ENE of Hasaki, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1539230846942,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
3632,NaN,3.1,1000h5gh,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.449,19.0,117.0,",us1000h5gh,",4.9,mb,...,reviewed,1538450871260,"M 4.9 - 53km ESE of Hitachi, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538581746455,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
3771,NaN,NaN,1000h7n9,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.925,NaN,167.0,",us1000h7n9,",4.5,mb,...,reviewed,1538422163330,"M 4.5 - 87km ESE of Kamaishi, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1539026579040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
3851,NaN,NaN,1000h7mm,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.288,NaN,98.0,",us1000h7mm,",4.7,mb,...,reviewed,1538406431250,"M 4.7 - 173km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539118704040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
4082,NaN,4.1,1000h4uw,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.178,7.0,79.0,",us1000h4uw,",4.8,mb,...,reviewed,1538360525340,"M 4.8 - 31km E of Chitose, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1539136962751,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
4192,NaN,2.2,1000h4r4,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.883,1.0,109.0,",us1000h4r4,",4.3,mb,...,reviewed,1538336412660,"M 4.3 - 50km NNE of Shizunai, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538367048207,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
4257,NaN,NaN,1000h7kb,https://earthquake.usgs.gov/fdsnws/event/1/que...,4.830,NaN,89.0,",us1000h7kb,",4.6,mb,...,reviewed,1538323620710,"M 4.6 - 213km SE of Hachijo-jima, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539103992040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
4409,NaN,4.1,1000h4k1,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.959,11.0,66.0,",us1000h4k1,",5.0,mww,...,reviewed,1538297644770,"M 5.0 - 33km NW of Shizunai, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538361706229,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
4846,NaN,2.7,1000h479,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.163,3.0,75.0,",us1000h479,",4.5,mb,...,reviewed,1538213154900,"M 4.5 - 25km ESE of Chitose, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538294859215,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
5655,NaN,NaN,1000h382,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.105,NaN,131.0,",us1000h382,",4.6,mb,...,reviewed,1538048754220,"M 4.6 - 156km ENE of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538050682040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
5915,NaN,NaN,1000h5rx,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.044,NaN,157.0,",us1000h5rx,",4.4,mb,...,reviewed,1538003928830,"M 4.4 - 78km ESE of Yamada, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1539400764040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
6769,NaN,2.7,2000hjkw,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.426,1.0,135.0,",us2000hjkw,",4.8,mb,...,reviewed,1537846261100,"M 4.8 - 58km SE of Ofunato, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1537908537284,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
6961,NaN,NaN,2000hjc4,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.482,NaN,116.0,",us2000hjc4,",4.7,mb,...,reviewed,1537799121060,"M 4.7 - 46km ENE of Hirara, Japan",0,earthquake,",geoserve,origin,phase-data,",480.0,1538419499040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7001,NaN,NaN,1000h3vt,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.418,NaN,87.0,",us1000h3vt,",4.3,mb,...,reviewed,1537792438760,"M 4.3 - 25km ESE of Muroran, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538375544040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7066,NaN,3.8,2000hja7,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.034,3.0,75.0,",us2000hja7,",4.4,mb,...,reviewed,1537780626560,"M 4.4 - 35km E of Tomakomai, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538238102308,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7145,NaN,NaN,2000hj80,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.242,NaN,140.0,",us2000hj80,",4.1,mb,...,reviewed,1537764836900,"M 4.1 - 97km N of Mombetsu, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1538716171040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7261,NaN,2.7,2000hj4d,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.421,2.0,106.0,",us2000hj4d,",4.1,mb,...,reviewed,1537738421220,"M 4.1 - 64km ESE of Owase, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1537740803336,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7381,NaN,3.3,2000hj04,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.373,10.0,137.0,",us2000hj04,",4.6,mb,...,reviewed,1537715134540,"M 4.6 - 9km ENE of Funaishikawa, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538332135138,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7408,NaN,1.0,2000hizb,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.396,1.0,137.0,",us2000hizb,",4.8,mb,...,reviewed,1537709390500,"M 4.8 - 65km SSE of Hasaki, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538329898836,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7652,NaN,NaN,1000h3qw,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.228,NaN,93.0,",us1000h3qw,",4.2,mb,...,reviewed,1537654508260,"M 4.2 - 164km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539135424040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7696,NaN,NaN,1000h3qp,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.223,NaN,146.0,",us1000h3qp,",4.0,mb,...,reviewed,1537640754840,"M 4.0 - 65km E of Shizunai, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539294775040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7807,NaN,NaN,1000h3qb,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.571,NaN,124.0,",us1000h3qb,",4.4,mb,...,reviewed,1537619327220,"M 4.4 - 67km NNE of Hachijo-jima, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538226419040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
7832,NaN,NaN,2000him5,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.263,NaN,37.0,",us2000him5,",5.3,mww,...,reviewed,1537613881810,"M 5.3 - 169km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1537614975040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8071,NaN,NaN,2000hic7,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.666,NaN,150.0,",us2000hic7,",4.4,mb,...,reviewed,1537550307820,"M 4.4 - 67km E of Nemuro, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1539122080040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8311,NaN,NaN,1000h3av,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.230,NaN,95.0,",us1000h3av,",4.4,mb,...,reviewed,1537487811890,"M 4.4 - 166km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538880454040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8324,NaN,NaN,2000hhxa,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.234,NaN,82.0,",us2000hhxa,",4.6,mb,...,reviewed,1537484762840,"M 4.6 - 167km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538969995040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8327,NaN,NaN,2000hhx3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.068,NaN,89.0,",us2000hhx3,",4.2,mb,...,reviewed,1537484169100,"M 4.2 - 34km ESE of Chitose, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538870822040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8376,NaN,NaN,1000h3am,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.272,NaN,91.0,",us1000h3am,",4.4,mb,...,reviewed,1537470382450,"M 4.4 - 171km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1539464832040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8431,NaN,NaN,2000hhlf,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.270,NaN,95.0,",us2000hhlf,",4.6,mb,...,reviewed,1537455447970,"M 4.6 - 171km E of Nago, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1537457187040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8550,NaN,NaN,2000hhgj,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.844,NaN,164.0,",us2000hhgj,",4.4,mb,...,reviewed,1537430889800,"M 4.4 - 105km ENE of Miyako, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1537510968040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8555,NaN,NaN,2000hhga,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.825,NaN,129.0,",us2000hhga,",4.6,mb,...,reviewed,1537429466000,"M 4.6 - 105km ENE of Miyako, Japan",0,earthquake,",geoserve,origin,phase-data,",600.0,1537430366040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8687,NaN,NaN,1000h2t5,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.485,NaN,147.0,",us1000h2t5,",4.2,mb,...,reviewed,1537392267190,"M 4.2 - 39km NE of Misawa, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1538890503040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
8965,NaN,2.7,2000hgwp,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.195,1.0,146.0,",us2000hgwp,",3.9,mwr,...,reviewed,1537315296630,"M 3.9 - 27km ESE of Kitaibaraki, Japan",0,earthquake,",dyfi,geoserve,moment-tensor,origin,phase-data,",540.0,1538624469951,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
9070,NaN,NaN,2000hgfj,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.315,NaN,141.0,",us2000hgfj,",4.7,mb,...,reviewed,1537289668660,"M 4.7 - 96km E of Hasaki, Japan",0,earthquake,",geoserve,origin,phase-data,",540.0,1537976170040,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
9083,NaN,3.1,2000hgf5,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.846,7.0,108.0,",us2000hgf5,",5.1,mww,...,reviewed,1537287709100,"M 5.1 - 23km ENE of Ishinomaki, Japan",0,earthquake,",dyfi,geoserve,moment-tensor,origin,phase-data,",540.0,1537974828415,https://earthquake.usgs.gov/earthquakes/eventp...,Japan
9198,NaN,3.4,2000hgaa,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.367,85.0,115.0,",us2000hgaa,",4.6,mb,...,reviewed,1537258271290,"M 4.6 - 3km ESE of Sugito, Japan",0,earthquake,",dyfi,geoserve,origin,phase-data,",540.0,1538220844777,https://earthquake.usgs.gov/earthquakes/eventp...,Japan

In [ ]:
df['magType'] == 'mb'

0       False
1       False
2       False
3       False
4       False
        ...
9327    False
9328    False
9329    False
9330    False
9331    False
Name: magType, Length: 9332, dtype: bool

In [ ]:
Japan_mb = df[(df['parsed_place'] == 'Japan') & (df['magType'] == 'mb')]
Japan_mb['mag'].quantile(0.95)

Japan_95 = Japan_mb['mag'].quantile(0.95)
print(Japan_95)

4.9

In [ ]:
# 2.b
Indonesia = df[df['parsed_place'] == 'Indonesia']
Indonesia['tsunami'].mean()*100

Indonesia_tsunami = Indonesia['tsunami'].mean()*100
print(Indonesia_tsunami)

23.12925170068027

In [ ]:
# 2.c
Nevada = df[df['parsed_place'] == 'Nevada']

Nevada_summary = Nevada.describe()
print(Nevada_summary)

             cdi        dmin       felt         gap         mag   mmi  \
count  15.000000  681.000000  15.000000  681.000000  681.000000  1.00
mean    2.440000    0.166199   2.400000  153.668120    0.500073  2.84
std     0.501142    0.166228   4.626013   68.735302    0.696710   NaN
min     2.000000    0.001000   1.000000   29.140000   -0.500000  2.84
25%     2.000000    0.053000   1.000000   97.380000   -0.100000  2.84
50%     2.200000    0.112000   1.000000  149.140000    0.400000  2.84
75%     2.900000    0.233000   1.000000  199.720000    0.900000  2.84
max     3.300000    1.414000  19.000000  355.910000    2.900000  2.84

              nst         rms         sig          time  tsunami     tz  \
count  681.000000  681.000000  681.000000  6.810000e+02    681.0  681.0
mean    12.618209    0.151986   10.970631  1.538314e+12      0.0 -480.0
std      9.866963    0.084662   19.607150  5.965637e+08      0.0    0.0
min      3.000000    0.000500    0.000000  1.537247e+12      0.0 -480.0
25%      6.000000    0.106900    0.000000  1.537854e+12      0.0 -480.0
50%     10.000000    0.146300    2.000000  1.538280e+12      0.0 -480.0
75%     16.000000    0.187100   12.000000  1.538821e+12      0.0 -480.0
max     61.000000    0.863400  129.000000  1.539461e+12      0.0 -480.0

            updated
count  6.810000e+02
mean   1.538402e+12
std    6.010951e+08
min    1.537307e+12
25%    1.537928e+12
50%    1.538428e+12
75%    1.538878e+12
max    1.539483e+12

In [ ]:
# 2.d
ring_locations = ['Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica', 'Guatemala', 'Mexico', 'Japan', 'Philippines',
                  'Indonesia', 'New Zealand', 'Canada', 'Fiji', 'Alaska', 'Washington', 'California', 'Russia',
                  'Taiwan', 'Tonga', 'Kermadec Islands']

In [ ]:
df['parsed_place'].isin(ring_locations)

0        True
1        True
2        True
3        True
4        True
        ...
9327     True
9328     True
9329    False
9330     True
9331     True
Name: parsed_place, Length: 9332, dtype: bool

In [ ]:
df['ring_of_fire'] = (df['parsed_place'].isin(ring_locations) | df['parsed_place'].str.contains('Antarctic', case = False, na = False))
print(df['ring_of_fire'])

0        True
1        True
2        True
3        True
4        True
        ...
9327     True
9328     True
9329    False
9330     True
9331     True
Name: ring_of_fire, Length: 9332, dtype: bool

In [ ]:
# 2.e
ring_of_fire_count = df['ring_of_fire'].sum()
ring_outside_of_fire_count = (~df['ring_of_fire']).sum()

print(ring_of_fire_count)
print(ring_outside_of_fire_count)

7188
2144

In [ ]:
# 2.f
ring_tsunami = df.loc[df['ring_of_fire'], 'tsunami'].sum()

print(ring_tsunami)

45